t1/ASP.NET/CaelumEstoque/CaelumEstoque/Models/CategoriaDoProduto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CaelumEstoque.Models
{
    public class CategoriaDoProduto
    {
        public int Id { get; set; }

        public String Nome { get; set; }

        public String Descricao { get; set; }
    }
}

t1/ASP.NET/CaelumEstoque/CaelumEstoque/Models/Produto.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CaelumEstoque.Models
{
    public class Produto
    {
        public int Id { get; set; }
        [Required, StringLength(20)]
        public String Nome { get; set; }
        
        public float Preco { get; set; }
        
        public CategoriaDoProduto Categoria { get; set; }
        
        public int? CategoriaId { get; set; }
        
        public String Descricao { get; set; }
        
        public int Quantidade { get; set; }
    }
}

t1/ASP.NET/CaelumEstoque/CaelumEstoque/Models/Usuario.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CaelumEstoque.Models
{
    public class Usuario
    {
        public int Id { get; set; }

        public string Nome { get; set; }

        public string Senha { get; set; }
    }
}

t1/ASP.NET/CaelumEstoque/CaelumEstoque/Controllers/CategoriaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CaelumEstoque.DAO;
using CaelumEstoque.Models;

namespace CaelumEstoque.Controllers
{
    public class CategoriaController : Controller
    {
        // GET: Categoria
        public ActionResult Index()
        {

            CategoriasDAO dao = new CategoriasDAO();
            IList<CategoriaDoProduto> categorias = dao.Lista();
            ViewBag.Categorias = categorias;
            return View();
        }

        public ActionResult Form()
        {

            return View();
        }

        [HttpPost]
        public ActionResult Adiciona(CategoriaDoProduto categorias)
        {
            CategoriasDAO dao = new CategoriasDAO();
            dao.Adiciona(categorias);

            return RedirectToAction("Index");
        }


    }
}

t1/ASP.NET/CaelumEstoque/CaelumEstoque/Controllers/ContadorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CaelumEstoque.Controllers
{
    public class ContadorController : Controller
    {
        // GET: Contador
        public ActionResult Index()
        {

            object valorNaSession = Session["contador"];
            int contador = Convert.ToInt32(valorNaSession);
            contador++;
            Session["contador"] = contador;
            return View(contador);
        }
    }
}

t1/ASP.NET/CaelumEstoque/CaelumEstoque/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CaelumEstoque.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/
        public ActionResult Index()
        {
            return View();
        }
	}
}

t1/ASP.NET/CaelumEstoque/CaelumEstoque/Controllers/LoginController.cs
using CaelumEstoque.DAO;
using CaelumEstoque.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CaelumEstoque.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Autentica(String login, String senha)
        {
            UsuariosDAO dao = new UsuariosDAO();
            Usuario usuario = dao.Busca(login, senha);
            if(usuario != null)
            {
                Session["usuarioLogado"] = usuario;
                return RedirectToAction("Index", "Produto");
            }

            return RedirectToAction("Index");
        }
    }
}

t1/ASP.NET/CaelumEstoque/CaelumEstoque/Controllers/ProdutoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CaelumEstoque.DAO;
using CaelumEstoque.Filtros;
using CaelumEstoque.Models;

namespace CaelumEstoque.Controllers
{
    [AutorizacaoFilter]
    public class ProdutoController : Controller
    {
        // GET: Produto
        [Route("produtos", Name ="ListaProdutos")]
        public ActionResult Index()
        {
                ProdutosDAO dao = new ProdutosDAO();
                IList<Produto> produtos = dao.Lista();
                return View(produtos);   
        }

        public ActionResult Form()
        {

            CategoriasDAO dao = new CategoriasDAO();
            IList<CategoriaDoProduto> categorias = dao.Lista();
            ViewBag.Categorias = categorias;
            ViewBag.Produto = new Produto();

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Adiciona(Produto produto)
        {
            int idDaInformatica = 1;
            if(produto.CategoriaId.Equals(idDaInformatica) && produto.Preco < 100)
            {
                ModelState.AddModelError("produto.Invalido", "Informatica com preço menor que 100 reais");
            }
            if (ModelState.IsValid)
            { 
            ProdutosDAO dao = new ProdutosDAO();
            dao.Adiciona(produto);

            return RedirectToAction("Index", "Produto");
            }
            else
            {
                ViewBag.Produto = produto;
                CategoriasDAO dao = new CategoriasDAO();
                ViewBag.Categorias = dao.Lista();
                return View("form");
            }
        }

        [Route("produtos/{id}", Name ="VisualizaProduto")]
        public ActionResult Visualiza(int id)
        {
            ProdutosDAO dao = new ProdutosDAO();
            Produto produto = dao.BuscaPorId(id);
            ViewBag.Produto = produto;
            return View();
        }


        public ActionResult DecrementaQtd(int id)
        {
            ProdutosDAO dao = new ProdutosDAO();
            Produto produto = dao.BuscaPorId(id);
            produto.Quantidade--;
            dao.Atualiza(produto);

            return Json(produto);

        }

    }
}

t1/ASP.NET/CaelumEstoque/CaelumEstoque/Views/Categoria/Form.cshtml
        <form action="/Categoria/Adiciona" method="post">

            <label for="nome">Nome:</label>
            <input id="nome" name="categorias.Nome" />

            <label for="descricao">Descrição:</label>
            <input id="descricao" name="categorias.Descricao" />

            <input type="submit" value="Cadastrar" />
        </form>

t1/ASP.NET/CaelumEstoque/CaelumEstoque/Views/Categoria/Index.cshtml
        <table>
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Nome</th>
                    <th>Quantidade</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var categoria in ViewBag.Categorias)
                {
                    <tr>
                        <td>@categoria.Id</td>
                        <td>@categoria.Nome</td>
                        <td>@categoria.Descricao</td>
                    </tr>
                }
            </tbody>
        </table>

t1/ASP.NET/CaelumEstoque/CaelumEstoque/Views/Contador/Index.cshtml
Contador : @Model

t1/ASP.NET/CaelumEstoque/CaelumEstoque/Views/Home/Index.cshtml
        <h1>Página Inicial da aplicação</h1>

t1/ASP.NET/CaelumEstoque/CaelumEstoque/Views/Login/Index.cshtml
<form action="/Login/Autentica" method="post" >

    <label for="login">Login: </label>
    <input type="text" name="login" id="login" class="form-control" />

    <label for="senha">Senha: </label>
    <input type="password" name="senha" id="senha"  class="form-control"/>

    <input type="submit" value="Autenticar" />
       
</form>

t1/ASP.NET/CaelumEstoque/CaelumEstoque/Views/Produto/Adiciona.cshtml
        <h1>Produto adicionado com sucesso!</h1>
 

t1/ASP.NET/CaelumEstoque/CaelumEstoque/Views/Produto/Form.cshtml
        <form action="/Produto/Adiciona" method="post">
            @Html.AntiForgeryToken()
            @Html.ValidationMessage("produto.Invalido")
            <label for="nome">Nome:</label>
            <input id="nome" name="produto.Nome" value="@ViewBag.Produto.Nome" class="form-control" />
            @Html.ValidationMessage("produto.Nome")

            <label for="preco">Preço:</label>
            <input id="preco" name="produto.Preco" value="@ViewBag.Produto.Preco" class="form-control"/>
            @Html.ValidationMessage("produto.Preco")

            <label for="quantidade">Quantidade:</label>
            <input id="quantidade" name="produto.Quantidade" value="@ViewBag.Produto.Quantidade" class="form-control"/>
            @Html.ValidationMessage("produto.Quantidade")

            <label for="descricao">Descrição:</label>
            <input id="descricao" name="produto.Descricao" value="@ViewBag.Produto.Descricao"class="form-control" />
            @Html.ValidationMessage("produto.Descricao")

            <label for="categoria">Categoria:</label>
            <select id="categoria" name="produto.CategoriaId" class="form-control">
                @foreach (var categoria in ViewBag.Categorias)
                {
                    <option value="@categoria.Id" selected="@categoria.Id.Equals(ViewBag.CategoriaId)">@categoria.Nome</option>
                }
            </select>

            <input type="submit" value="Cadastrar" />
        </form>

t1/ASP.NET/CaelumEstoque/CaelumEstoque/Views/Produto/Index.cshtml
@model IList<CaelumEstoque.Models.Produto>


<table class="table table-hover">
    <thead>
        <tr>
            <th>Id</th>
            <th>Nome</th>
            <th>Quantidade</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var produto in Model)
        {
            <tr>
                <td>@produto.Id</td>
                @*<td>@Html.ActionLink(produto.Nome, "Visualiza", new { id = produto.Id })</td>*@
                <td>@Html.RouteLink(produto.Nome, "VisualizaProduto", new { id = produto.Id })</td>

                <td id="quantidade@(produto.Id)">@produto.Quantidade</td>
                @*<td>@Html.RouteLink("Decrementar", "DecrementaProduto", new { id = produto.Id })</td>*@
                <td><a href="#" onclick="decrementa(@produto.Id);">Decrementar</a></td>
            </tr>
        }
    </tbody>
</table>


<script type="text/javascript" src="~/Scripts/jquery-1.10.2.js"></script>
<script type="text/javascript">
    function decrementa(produtoId) {
        var url = "@Url.Action("DecrementaQtd", "Produto")";
        var params = { id : produtoId };
        $.post(url, params, atualiza);

    }

    function atualiza(resposta) {
        $("#quantidade" + resposta.Id).html(resposta.Quantidade);
    }

</script>

t1/ASP.NET/CaelumEstoque/CaelumEstoque/Views/Produto/Visualiza.cshtml
    <div>
        Id: @ViewBag.Produto.Id<br />
        Nome: @ViewBag.Produto.Nome<br />
        Quantidade: @ViewBag.Produto.Quantidade<br />
        Preço: @ViewBag.Produto.Preco <br />
        Descrição: @ViewBag.Produto.Descricao<br />
        Categoria: @ViewBag.Produto.Categoria.Nome<br />

        @Html.ActionLink("Voltar para a lista de produtos", "Index", "Produto");
    </div>

t1/ASP.NET/CaelumEstoque/CaelumEstoque/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>_Layout</title>
    <link rel="stylesheet" href="~/Content/Css/bootstrap.css" />
    <link rel="stylesheet" href="~/Content/Css/Site.css" />
</head>
<body>

    <div class="container">
        <div class="header">
            <ul class="nav nav-pills pull-right">
                <li>@Html.ActionLink("Produtos", "Index", "Produto")</li>
                <li>@Html.ActionLink("Categorias", "Index", "Categoria")</li>
            </ul>
            <h3 class="text-muted">Caelum Estoque</h3>
        </div>
    </div>

    <div id="conteudo">
        @RenderBody()
    </div>
</body>
</html>